"use client";

import Image from "next/image";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { arrayMove, SortableContext, useSortable, verticalListSortingStrategy } from "@dnd-kit/sortable";
import { DndContext, DragEndEvent, PointerSensor, useSensor, useSensors } from "@dnd-kit/core";
import { CSS } from "@dnd-kit/utilities";
import { Building2, ExternalLink, GripVertical, ImagePlus, LogOut, MessageCircle, Pencil, Pin, Plus, Trash2, X } from "lucide-react";

type Foto = { id?: number; url: string; ordem?: number };
type FotoPendente = { id: string; file: File; url: string };
type Imovel = { id: number; titulo: string; tipo: string; cidade: string; estado: string; descricao: string | null; preco: string | number; quartos: number | null; banheiros: number | null; area: number | null; imagemUrl: string | null; disponivel: boolean; destaque: boolean; ordem: number; fotos?: Foto[] };
type Formulario = Omit<Imovel, "id" | "preco" | "imagemUrl" | "disponivel" | "destaque" | "ordem" | "fotos"> & { preco: string; imagemUrl: string; disponivel: boolean; destaque: boolean; ordem: number; fotos: string[] };
const placeholder = "/imagens/imovel-placeholder.svg";
const vazio: Formulario = { titulo: "", tipo: "Casa", cidade: "Curitiba", estado: "PR", descricao: "", preco: "", quartos: null, banheiros: null, area: null, imagemUrl: placeholder, disponivel: true, destaque: false, ordem: 0, fotos: [] };
const whatsapp = "https://wa.me/5541992371353";

function Login({ onSuccess }: { onSuccess: () => void }) {
  const [username, setUsername] = useState("admin"); const [password, setPassword] = useState(""); const [erro, setErro] = useState(""); const [carregando, setCarregando] = useState(false);
  async function entrar(event: FormEvent) { event.preventDefault(); setCarregando(true); setErro(""); const resposta = await fetch("/api/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username, password }) }); const dados = await resposta.json().catch(() => ({})); if (!resposta.ok) setErro(dados.erro || "Não foi possível entrar."); else onSuccess(); setCarregando(false); }
  return <main className="admin-login"><div className="login-card"><div className="login-mark"><Building2 size={28} /></div><span className="admin-kicker">ÁREA RESTRITA</span><h1>Acessar painel</h1><p>Gerencie os imóveis da Andréia Corretora.</p><form onSubmit={entrar}><label>Usuário<input value={username} onChange={(e) => setUsername(e.target.value)} required autoComplete="username" /></label><label>Senha<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required autoComplete="current-password" /></label><button className="btn gold form-submit" disabled={carregando}>{carregando ? "Entrando..." : "Entrar no painel"}</button>{erro && <p className="admin-error">{erro}</p>}</form><a className="login-site-link" href="/">← Voltar para o site</a></div></main>;
}

function SortablePhoto({ foto, index, onRemove }: { foto: string; index: number; onRemove: () => void }) {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({ id: foto });
  return <div ref={setNodeRef} className={`sortable-photo${isDragging ? " dragging" : ""}`} style={{ transform: CSS.Transform.toString(transform), transition }}><Image src={foto} alt={`Foto ${index + 1}`} fill sizes="180px" /><span className="photo-order">{index === 0 ? "Foto capa" : index + 1}</span><button type="button" className="drag-handle" {...attributes} {...listeners} aria-label="Arrastar foto"><GripVertical size={17} /></button><button type="button" className="remove-photo" onClick={onRemove} aria-label="Excluir foto"><X size={15} /></button></div>;
}

function SortablePendingPhoto({ foto, index, onRemove }: { foto: FotoPendente; index: number; onRemove: () => void }) {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({ id: foto.id });
  return <div ref={setNodeRef} className={`sortable-photo${isDragging ? " dragging" : ""}`} style={{ transform: CSS.Transform.toString(transform), transition }}>
    <Image src={foto.url} alt={`Nova foto ${index + 1}`} fill sizes="180px" />
    <span className="photo-order">{index === 0 ? "Será a capa" : index + 1}</span>
    <button type="button" className="drag-handle" {...attributes} {...listeners} aria-label="Arrastar foto"><GripVertical size={17} /></button>
    <button type="button" className="remove-photo" onClick={onRemove} aria-label="Remover foto"><X size={15} /></button>
  </div>;
}

function SortableProperty({ imovel, onEdit, onRemove }: { imovel: Imovel; onEdit: () => void; onRemove: () => void }) {
  const { attributes, listeners, setNodeRef, transform, transition } = useSortable({ id: imovel.id });
  return <article ref={setNodeRef} className="property-item" style={{ transform: CSS.Transform.toString(transform), transition }}>
    <div className="property-image"><Image src={imovel.fotos?.[0]?.url || imovel.imagemUrl || placeholder} alt="" fill sizes="300px" /><span className={imovel.disponivel ? "status available" : "status unavailable"}>{imovel.disponivel ? "Publicado" : "Oculto"}</span>{imovel.destaque && <span className="featured-badge">Destaque</span>}</div>
    <div className="property-content"><span>{imovel.tipo} · {imovel.cidade}/{imovel.estado}</span><h3>{imovel.titulo}</h3><strong>{Number(imovel.preco) > 0 ? Number(imovel.preco).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }) : "Consulte o valor"}</strong><div className="property-actions"><button type="button" className="drag-handle" {...attributes} {...listeners} aria-label="Arrastar imóvel"><GripVertical size={14} /></button><button type="button" onClick={onEdit}><Pencil size={14} /> Editar</button><a className="whatsapp-card" href={`${whatsapp}?text=${encodeURIComponent(`Olá, tenho interesse no imóvel: ${imovel.titulo}`)}`} target="_blank" rel="noopener noreferrer"><MessageCircle size={14} /> WhatsApp</a><button className="delete-button" type="button" onClick={onRemove}><Trash2 size={14} /></button></div></div>
  </article>;
}

export default function AdminPanel() {
  const [autenticado, setAutenticado] = useState<boolean | null>(null); const [imoveis, setImoveis] = useState<Imovel[]>([]); const [form, setForm] = useState<Formulario>(vazio); const [editando, setEditando] = useState<number | null>(null); const [arquivos, setArquivos] = useState<FotoPendente[]>([]); const [mensagem, setMensagem] = useState(""); const [carregando, setCarregando] = useState(false); const sensores = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }));
  async function carregar() { const resposta = await fetch("/api/imoveis", { cache: "no-store" }); if (resposta.ok) setImoveis(await resposta.json()); else if (resposta.status === 401) setAutenticado(false); }
  useEffect(() => { fetch("/api/admin/session").then((r) => r.json()).then((d) => { setAutenticado(d.autenticado); if (d.autenticado) carregar(); }); }, []);
  function alterar<K extends keyof Formulario>(campo: K, valor: Formulario[K]) { setForm((atual) => ({ ...atual, [campo]: valor })); }
  function adicionarArquivos(selecionados: File[]) { const validos = selecionados.filter((arquivo) => ["image/jpeg", "image/png", "image/webp"].includes(arquivo.type) && arquivo.size <= 5 * 1024 * 1024); if (validos.length !== selecionados.length) setMensagem("Algumas fotos foram ignoradas: use JPG, PNG ou WebP de até 5 MB."); setArquivos((atuais) => [...atuais, ...validos.map((file) => ({ file, url: URL.createObjectURL(file), id: `${file.name}-${file.size}-${file.lastModified}-${crypto.randomUUID()}` }))]); }
  function selecionarArquivos(event: ChangeEvent<HTMLInputElement>) { adicionarArquivos(Array.from(event.target.files || [])); event.target.value = ""; }
  async function enviarImagens() { const urls = [...form.fotos]; for (const pendente of arquivos) { const dados = new FormData(); dados.append("file", pendente.file); const resposta = await fetch("/api/upload", { method: "POST", body: dados }); const resultado = await resposta.json().catch(() => null) as { erro?: string; url?: string } | null; if (!resposta.ok || !resultado?.url) throw new Error(resultado?.erro || "Não foi possível enviar uma foto."); urls.push(resultado.url); } return urls; }
  function iniciarEdicao(imovel: Imovel) { const fotos = imovel.fotos?.map((foto) => foto.url) || (imovel.imagemUrl ? [imovel.imagemUrl] : []); setEditando(imovel.id); setArquivos([]); setForm({ titulo: imovel.titulo, tipo: imovel.tipo, cidade: imovel.cidade, estado: imovel.estado, descricao: imovel.descricao || "", preco: String(Number(imovel.preco)), quartos: imovel.quartos, banheiros: imovel.banheiros, area: imovel.area, imagemUrl: fotos[0] || placeholder, disponivel: imovel.disponivel, destaque: imovel.destaque, ordem: imovel.ordem, fotos }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function limparFormulario() { setForm(vazio); setEditando(null); setArquivos([]); }
  async function salvar(event: FormEvent) { event.preventDefault(); setCarregando(true); setMensagem(""); try { const fotos = await enviarImagens(); const resposta = await fetch(editando ? `/api/imoveis/${editando}` : "/api/imoveis", { method: editando ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, fotos, imagemUrl: fotos[0] || placeholder, preco: Number(form.preco) }) }); const resultado = await resposta.json().catch(() => null) as { erro?: string } | null; if (!resposta.ok) throw new Error(resultado?.erro || "Não foi possível salvar o imóvel."); setMensagem(editando ? "Imóvel atualizado com sucesso." : "Imóvel cadastrado com sucesso."); limparFormulario(); carregar(); } catch (erro) { setMensagem(erro instanceof Error ? erro.message : "Não foi possível salvar o imóvel."); } finally { setCarregando(false); } }
  function reordenar(event: DragEndEvent) { if (!event.over || event.active.id === event.over.id) return; setForm((atual) => { const origem = atual.fotos.indexOf(String(event.active.id)); const destino = atual.fotos.indexOf(String(event.over!.id)); return { ...atual, fotos: arrayMove(atual.fotos, origem, destino), imagemUrl: arrayMove(atual.fotos, origem, destino)[0] || placeholder }; }); }
  async function remover(id: number) { if (!window.confirm("Deseja remover este imóvel?")) return; const resposta = await fetch(`/api/imoveis/${id}`, { method: "DELETE" }); if (resposta.ok) { setMensagem("Imóvel removido."); carregar(); } else setMensagem("Não foi possível remover o imóvel."); }
  async function reordenarImoveis(event: DragEndEvent) { if (!event.over || event.active.id === event.over.id) return; const origem = imoveis.findIndex((imovel) => imovel.id === Number(event.active.id)); const destino = imoveis.findIndex((imovel) => imovel.id === Number(event.over!.id)); const ordenados = arrayMove(imoveis, origem, destino); setImoveis(ordenados); const resposta = await fetch("/api/imoveis/ordem", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ids: ordenados.map((imovel) => imovel.id) }) }); if (!resposta.ok) { setMensagem("Não foi possível salvar a ordem dos imóveis."); carregar(); } }
  async function sair() { await fetch("/api/admin/logout", { method: "POST" }); setAutenticado(false); }
  if (autenticado === null) return <main className="admin-loading">Carregando painel...</main>; if (!autenticado) return <Login onSuccess={() => { setAutenticado(true); carregar(); }} />;
  return <main className="admin-shell"><header className="admin-header"><div className="admin-header-inner"><div className="brand-admin"><div className="brand-icon"><Building2 size={21} /></div><div><span className="admin-eyebrow">ÁREA RESTRITA</span><h1>Painel de imóveis</h1></div></div><div className="admin-header-actions"><a className="admin-back" href="/" target="_blank" rel="noopener noreferrer"><ExternalLink size={15} /> Ver site</a><button className="logout-button" onClick={sair}><LogOut size={15} /> Sair</button></div></div></header>
    <div className="admin wrap"><section className="admin-intro"><div><p className="admin-kicker">Gestão do catálogo</p><h2>Olá, Andréia</h2><p>Cadastre imóveis e organize suas fotos.</p></div><div className="admin-stat"><strong>{imoveis.length}</strong><span>imóveis cadastrados</span></div></section>
      <section className="admin-layout"><form className="property-form" onSubmit={salvar}><div className="form-heading"><div><span className="admin-kicker">{editando ? "EDIÇÃO" : "NOVO ANÚNCIO"}</span><h2>{editando ? "Editar imóvel" : "Adicionar imóvel"}</h2></div>{editando && <button className="text-button" type="button" onClick={limparFormulario}><X size={14} /> Cancelar</button>}</div>
        <div className="form-grid"><label>Título<input value={form.titulo} onChange={(e) => alterar("titulo", e.target.value)} required /></label><label>Tipo<select value={form.tipo} onChange={(e) => alterar("tipo", e.target.value)}><option>Casa</option><option>Sobrado</option><option>Apartamento</option><option>Terreno</option><option>Comercial</option></select></label><label>Cidade<input value={form.cidade} onChange={(e) => alterar("cidade", e.target.value)} required /></label><label>Estado<input value={form.estado} onChange={(e) => alterar("estado", e.target.value)} maxLength={2} required /></label></div>
        <label>Descrição<textarea value={form.descricao || ""} onChange={(e) => alterar("descricao", e.target.value)} rows={4} /></label><div className="form-grid"><label>Preço (R$)<input type="number" min="0" step="0.01" value={form.preco} onChange={(e) => alterar("preco", e.target.value)} required /></label><label>Área (m²)<input type="number" min="0" value={form.area ?? ""} onChange={(e) => alterar("area", e.target.value ? Number(e.target.value) : null)} /></label><label>Quartos<input type="number" min="0" value={form.quartos ?? ""} onChange={(e) => alterar("quartos", e.target.value ? Number(e.target.value) : null)} /></label><label>Banheiros<input type="number" min="0" value={form.banheiros ?? ""} onChange={(e) => alterar("banheiros", e.target.value ? Number(e.target.value) : null)} /></label></div>
        <div className="upload-box" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); adicionarArquivos(Array.from(event.dataTransfer.files)); }}><div><strong><ImagePlus size={17} /> Fotos do imóvel</strong><p>Selecione ou solte várias imagens · JPG, PNG ou WebP · até 5 MB cada</p><label className="upload-button">Adicionar fotos<input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={selecionarArquivos} /></label></div>{arquivos.length > 0 && <span className="upload-count">{arquivos.length} nova(s)</span>}</div>
        {form.fotos.length > 0 && <div className="photo-section"><strong>Fotos salvas <span>Arraste para reordenar</span></strong><DndContext sensors={sensores} onDragEnd={reordenar}><SortableContext items={form.fotos} strategy={verticalListSortingStrategy}><div className="photo-sortable-grid">{form.fotos.map((foto, index) => <SortablePhoto key={foto} foto={foto} index={index} onRemove={() => alterar("fotos", form.fotos.filter((_, fotoIndex) => fotoIndex !== index))} />)}</div></SortableContext></DndContext></div>}
        {arquivos.length > 0 && <div className="photo-section"><strong>Novas fotos <span>Estas serão adicionadas na ordem abaixo</span></strong><DndContext sensors={sensores} onDragEnd={(event) => { if (!event.over || event.active.id === event.over.id) return; setArquivos((atuais) => { const origem = atuais.findIndex((foto) => foto.id === event.active.id); const destino = atuais.findIndex((foto) => foto.id === event.over!.id); return arrayMove(atuais, origem, destino); }); }}><SortableContext items={arquivos.map((foto) => foto.id)} strategy={verticalListSortingStrategy}><div className="photo-sortable-grid">{arquivos.map((foto, index) => <SortablePendingPhoto key={foto.id} foto={foto} index={index} onRemove={() => { URL.revokeObjectURL(foto.url); setArquivos((atuais) => atuais.filter((item) => item.id !== foto.id)); }} />)}</div></SortableContext></DndContext></div>}
        <label className="checkbox-label"><input type="checkbox" checked={form.destaque} onChange={(e) => alterar("destaque", e.target.checked)} /> <Pin size={15} /> Marcar como destaque (fica primeiro)</label><label className="checkbox-label"><input type="checkbox" checked={form.disponivel} onChange={(e) => alterar("disponivel", e.target.checked)} /> Exibir este imóvel no site</label><button className="btn gold form-submit" disabled={carregando}><Plus size={17} /> {carregando ? "Enviando fotos..." : editando ? "Salvar alterações" : "Cadastrar imóvel"}</button>{mensagem && <p className="admin-message">{mensagem}</p>}</form>
        <aside className="admin-help"><strong>Como funciona</strong><p>Adicione várias fotos e arraste a primeira posição para escolher a capa.</p><a className="whatsapp-admin" href={whatsapp} target="_blank" rel="noopener noreferrer"><MessageCircle size={17} /> Falar no WhatsApp</a></aside></section>
      <section className="property-list"><div className="list-heading"><div><span className="admin-kicker">CATÁLOGO</span><h2>Imóveis cadastrados</h2><p>Arraste os anúncios para definir a ordem. Os destaques ficam sempre antes dos demais.</p></div><span className="list-count">{imoveis.length} anúncios</span></div><DndContext sensors={sensores} onDragEnd={reordenarImoveis}><SortableContext items={imoveis.map((imovel) => imovel.id)} strategy={verticalListSortingStrategy}><div className="property-grid">{imoveis.map((imovel) => <SortableProperty key={imovel.id} imovel={imovel} onEdit={() => iniciarEdicao(imovel)} onRemove={() => remover(imovel.id)} />)}</div></SortableContext></DndContext></section>
    </div></main>;
}
